name: Basic CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    strategy:
      matrix:
        features: ["", "--features eh1_0_alpha"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          profile: minimal
          override: true
      - run: cargo install flip-link
      - run: cargo build --all
      - run: cargo build --all --release

  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
      - run: cargo clippy -- -Dwarnings

  format:
    name: format
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
      - run: cargo fmt -- --check
