on: [push, pull_request]
name: Build and Test check
jobs:
  builds:
    name: Build checks
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        mode: ["", "--release"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true
          profile: minimal
      - name: Build workspace
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.mode }}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --tests --target x86_64-unknown-linux-gnu
      - name: Test docs
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --target x86_64-unknown-linux-gnu
      - name: Clean
        uses: actions-rs/cargo@v1
        with:
          command: clean
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv6m-none-eabi
          override: true
          profile: minimal
      - name: Install cargo-hack
        run: |
          curl -sSL https://github.com/taiki-e/cargo-hack/releases/download/v0.6.17/cargo-hack-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C ~/.cargo/bin
      - name: Install cargo-udeps
        run: |
          curl -sSL https://github.com/est31/cargo-udeps/releases/download/v0.1.55/cargo-udeps-v0.1.55-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - --strip-components=2 -C ~/.cargo/bin ./cargo-udeps-v0.1.55-x86_64-unknown-linux-gnu/cargo-udeps
      - name: Run cargo-udeps
        run: cargo hack udeps --optional-deps --each-feature

