on: [push, pull_request]
name: Build and Test check
jobs:
  builds:
    name: Build checks
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mode: ["", "--release"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true
          profile: minimal
      - name: Build workspace
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.mode }}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --tests --target x86_64-unknown-linux-gnu
      - name: Test docs
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --target x86_64-unknown-linux-gnu
      - name: Clean
        uses: actions-rs/cargo@v1
        with:
          command: clean
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv6m-none-eabi
          override: true
          profile: minimal
      - name: Check unused deps
        uses: aig787/cargo-udeps-action@v1
        with:
          version: latest
          args: ${{ matrix.mode }}

